### ISSUE TITLE
ipfs-update won't work in private network

### ISSUE THREAD

**Issue by khachatur-s** [ipfs/ipfs-update#100]
IPFS Version information: 0.4.17
ipfs-update: Version information: 1.5.3-dev
Type: Feature Request
Severity: Enhancement

ipfs-update won't work when enabling IPFS [Private Networks](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks) feature. 
It's logical, 'cause ipfs-update uses local ipfs daemon for data transfer and this IPFS [Private Networks](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#private-networks) feature assumes communicating only with private nodes, but on the other hand it would be very useful to be able to use ipfs-update assuming that the private nodes have access to the web.
Maybe it worth to add another update method alongside ipfs?

**Comment by hsanjuan** [comment]
This tool uses the local ipfs daemon to fetch the files, but if that is not available, it fails back to the public gateways. I suggest to stop the local ipfs daemon before running ipfs-update.

Closing this for the moment, but if you want to take a stab at adding a command flag to download directly from http, go ahead :)
