### ISSUE TITLE
How do i change ipfs-update tmp directory from /tmp/ipfs-updatexxxx to other place ?

### ISSUE THREAD

**Issue by alzxcv43210** [ipfs/ipfs-update#101]
Hi All
My arm linux installed ipfs, when i try to ipfs-update it told to me ...

xxx:/mnt/md1/admin/ipfs-update# ./ipfs-update --verbose fetch
looking up 'latest'
  - fetching "/ipns/dist.ipfs.io/go-ipfs/versions"
fetching url: https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/versions
fetching go-ipfs version v0.4.18
  - using GOOS=linux and GOARCH=arm
  - fetching "/ipns/dist.ipfs.io/go-ipfs/v0.4.18/go-ipfs_v0.4.18_linux-arm.tar.gz"
fetching url: https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/v0.4.18/go-ipfs_v0.4.18_linux-arm.tar.gz
  - writing to /tmp/ipfs-update730619477/go-ipfs_v0.4.18_linux-arm.tar.gz
ERROR: failed to fetch binary:  write /tmp/ipfs-update730619477/go-ipfs_v0.4.18_linux-arm.tar.gz: no space left on device

Because my /tmp is tmpfs and just 16M

xxx:/mnt/md1/admin/ipfs-update# df /tmp
Filesystem     1K-blocks  Used Available Use% Mounted on
tmpfs              15912 15908         4 100% /tmp

How do i change ipfs-update temp directory from /tmp to other place ?

Thanks,
AL

**Comment by Stebalien** [comment]
You can set the TMPDIR environment variable to change the default temporary directory (note: this will apply to applications other than IPFS as well).

You should also consider increasing the size of /tmp. A lot of applications are going to have trouble with a 16MiB temporary directory.

**Comment by alzxcv43210** [comment]
That solved my problem.

Thanks a lot.
