### ISSUE TITLE
Unable to install ipfs-update

### ISSUE THREAD

**Issue by niharrs** [ipfs/ipfs-update#104]
<img width="571" alt="Screenshot 2019-05-12 at 10 04 04 PM" src="https://user-images.githubusercontent.com/24189168/57585156-e0e48300-7501-11e9-96bc-c9c54a8640cf.png">

Go version: `go version go1.11.1 darwin/amd64`

**Comment by djdv** [comment]
It looks like `$GOPATH/bin` is missing from your `$PATH`. So even though `ipfs-update` is installed, you need to tell your shell where it was installed to.
https://golang.org/doc/code.html#GOPATH
(By default this would be `~/go/bin/ipfs-update`)
