### ISSUE TITLE
https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/versions down?

### ISSUE THREAD

**Issue by mitra42** [ipfs/ipfs-update#105]
I'm seeing failures to install IPFS with `https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/versions` not returning, (which unfortunately is blocking our Docker update for everything else). 

Does anyone know if this is a temporary glitch, or something permanent ?

**Comment by mitra42** [comment]
Looks like its still happening, the failing line in docker is 
```
/bin/sh -c go get -u -v github.com/ipfs/ipfs-update      && ipfs-update install latest
```
Which fails with 
```
ERROR: error resolving 'latest':  http.DefaultClient.Do error: Get https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/versions: net/http: TLS handshake timeout
```
It seems that `https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/versions` has very variable performance, 
Maybe ipfs-update needs to get its list of versions from somewhere more reliable than IPNS ?

**Comment by Kubuxu** [comment]
It isn't IPNS, it is the gateways having intermittent problems. We are working on resolving them.

**Comment by mitra42** [comment]
Thanks for clarification - but still begs a rephrase question should ipfs-update depend on the gateways which are somewhat unstable (in the way of any rapidly moving development). 
The importance isn't for update of a running IPFS, its more that this process is also used to make sure Docker installs get the latest IPFS.

**Comment by mitra42** [comment]
I can confur this doesn't look like a problem with just IPNS as URLs like: 
`https://dist.ipfs.io/go-ipfs/v0.4.21/go-ipfs_v0.4.21_linux-arm.tar.gz` 
are failing

**Comment by hechty** [comment]
PS C:\go-ipfs> .\ipfs-update.exe versions
ERROR: failed to query versions:  http.DefaultClient.Do error: Get https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/versions: dial tcp 69.63.184.14:443: connectex: No connection could be made because the target machine actively refused it.

**Comment by Stebalien** [comment]
The gateway instability has mostly been fixed (for now).

---

@hechty ipfs.io is blocked in china. You'll have to download IPFS from GitHub: https://github.com/ipfs/go-ipfs/releases

**Comment by 0zAND1z** [comment]
So this repeated again today when I was setting up a new IPFS node:

![Screenshot from 2021-08-01 13-51-04](https://user-images.githubusercontent.com/11145839/127764480-1bd5aea7-2529-42d4-bcb4-5c7629c63bf2.png)

In the interest of reducing dependency on a single gateway, I have a suggestion:
Let us have a list of "trusted" fallback gateways such as `dweb.link` in case `ipfs-update` fails to dial the main gateway (`ipfs.io`) .

When I dialed using dweb.link, I get the version list, without having a single point of failure:
![Screenshot from 2021-08-01 13-56-36](https://user-images.githubusercontent.com/11145839/127764598-e6361c02-fc0b-4283-bf89-043d17b7960c.png)
