### ISSUE TITLE
Dependency md2man is down

### ISSUE THREAD

**Issue by collincusce** [ipfs/ipfs-update#109]
Hey guys,

Tried to install today and this is what I get:

```sh
ccusce@AVAccusce:~$ go get -u github.com/ipfs/ipfs-update
package github.com/cpuguy83/go-md2man/v2/md2man: cannot find package "github.com/cpuguy83/go-md2man/v2/md2man" in any of:
	/home/ccusce/.gvm/gos/go1.10/src/github.com/cpuguy83/go-md2man/v2/md2man (from $GOROOT)
	/home/ccusce/.gvm/pkgsets/go1.10/global/src/github.com/cpuguy83/go-md2man/v2/md2man (from $GOPATH)
```

I checked out the repo https://github.com/cpuguy83/go-md2man/v2/md2ma is down but the master branch is up. Perhaps you meant to reference that? There's also a v2 release but it only supports golang v11 or higher, which is not in-line with the ipfs requirements from what I can tell (which is v1.10+, no?). https://github.com/cpuguy83/go-md2man/releases/tag/v2.0.0

**Comment by hsanjuan** [comment]
I cannot reproduce this. go get install works for me on latest Go1.13. Re-open if anything new comes up.
