### ISSUE TITLE
'ipfs-update install latest' doesn't appear to update

### ISSUE THREAD

**Issue by ncorder** [ipfs/ipfs-update#117]
**Log**:

```
[ec2-user@host ipfs-update-binaries]$ sudo /usr/local/bin/ipfs-update install latest
Already have version v0.4.23-rc2 installed, skipping.

Installation complete!
[ec2-user@host ipfs-update-binaries]$ ipfs version
ipfs version 0.4.17
[ec2-user@host ipfs-update-binaries]$ 
```

When running the command as `ipfs-update`:

```
[ec2-user@host ipfs-update-binaries]$ sudo ipfs-update install latest
sudo: ipfs-update: command not found
[ec2-user@host ipfs-update-binaries]$ ipfs-update install latest
fetching go-ipfs version v0.4.23-rc2
binary downloaded, verifying...
success! tests all passed.
stashing old binary
install failed, reverting changes...
could not move old binary: remove /usr/local/bin/ipfs: permission denied
[ec2-user@host ipfs-update-binaries]$ 
```

```
[ec2-user@host ipfs-update-binaries]$ ipfs-update version
v0.4.17
[ec2-user@host ipfs-update-binaries]$ 
```
______________

**Description**: The log states it all.

**OS**: Red Hat GNU/Linux v8

**How was program installed?**: Using the binary with `./install.sh`.

**Comment by hsanjuan** [comment]
hey @ncorder , I am suspecting that you have two ipfs binaries laying around, one taking precedence over other (depending on running with `sudo` or not). Run:

What are `which ipfs` and `sudo which ipfs` showing?

**Comment by Stebalien** [comment]
So, we're _supposed_ to fail in this case. When we install IPFS, we check to see if there's an existing copy. If there is, we try to move it out of the way and replace it.

**Comment by Kirol54** [comment]
I have a bit different issue but the title would be the same so commenting here.

I have dockefile for running private ipfs node, and it recently started failing at :

`Step 11/15 : RUN ipfs-update install latest`
` ---> Running in f0cebf0xxxx`
`ERROR: fetching resource: 404 Not Found`
`ERROR: error resolving 'latest':  404 Not Found: ipfs resolve -r /ipns/ipfs.io/ipns/dist.ipfs.io/go-ipfs/versions: no link named "ipns" under bafybeibdwwmb725qy4yph56jg4bs6uimcst5hnvuraarowgdaytzmgsw24`

**Comment by hsanjuan** [comment]
I'm going to close this since no updates since january...
