### ISSUE TITLE
ipfs update install for OSX generates "ERROR: could not find good install location"

### ISSUE THREAD

**Issue by erich-comsIO** [ipfs/ipfs-update#122]
On OSX - there is the identical issue that was closed for linux:
https://github.com/ipfs/ipfs-update/issues/73

Just like in that report, exporting a modified go path to use expansion (~/go/bin) was the work around.

Seems like more testing for releases is in order.

**Comment by Stebalien** [comment]
What do you mean "to use expansion"? If `$HOME/go/bin` isn't in your path, `ipfs-update` will look for an alternative install location. If it can't find any good install location, it'll return that error.

Please re-run ipfs-update with `--verbose` and post the log.

**Comment by erich-comsIO** [comment]
Sorry for the very slow response - as per my original post, I modified the path to use /go/bin in my home directly through expansion (~), and that made the application run. I guess the go path in my shell was different and update didn't find the good installation - but it's been so long I don't remember, so obviously i'll just close this out. Sorry for any confusion.
