### ISSUE TITLE
"ipfs-update install latest" fails to run on docker

### ISSUE THREAD

**Issue by Kirol54** [ipfs/ipfs-update#125]
## Description:
I have dockefile for running private ipfs node, and it recently started failing at :

#### Command Output:

```
Step 11/15 : RUN ipfs-update install latest
---> Running in f0cebf0xxxx
ERROR: fetching resource: 404 Not Found
ERROR: error resolving 'latest': 404 Not Found: ipfs resolve -r /ipns/ipfs.io/ipns/dist.ipfs.io/go-ipfs/versions: no link named "ipns" under bafybeibdwwmb725qy4yph56jg4bs6uimcst5hnvuraarowgdaytzmgsw24
```

#### Edit: I just tried passing version number instead of "latest" - same error 
```dist.ipfs.io/go-ipfs/v1.5.3/go-ipfs_v1.5.3_linux-arm.tar.gz: no link named "ipns" under bafyb```

**Comment by Stebalien** [comment]
Have you set the IPFS_DIST_PATH environment variable anywhere?

**Comment by hsanjuan** [comment]
This may have been a transient issue with the public gateways. Can you verify and close if it's fixed?

**Comment by Kirol54** [comment]
no, I haven't set it anywhere

install latest started to work as of today morning, but passing version number (i.e 1.5.0) still fails. 
sorry, could have been just transient as you say

**Comment by hsanjuan** [comment]
>  but passing version number (i.e 1.5.0) still fails.

@Kirol54  It works for me. Is your ipfs-update version up to date? (note 1.5.0 is not a go-ipfs version).

**Comment by Kirol54** [comment]
my mistake, I was passing version number of ipfs-update rather than go-ipfs.

and I said before, `ipfs-update install latest` started to work again few hours ago
