### ISSUE TITLE
v1.6.0 doesn't run revert migration as stated in change log

### ISSUE THREAD

**Issue by bertrandfalguiere** [ipfs/ipfs-update#129]
#### Version information:
ipfs-update version 1.6.0
OS: Ubuntu 20.04

#### Description:
1) I had go-ipfs 0.4.23.
2) I ran ipfs-update install 0.5.0-rc4. IPFS and repo were upgraded as expected. 
3) I ran a downgrade back to 0.4.23. 

Expected: A revert migration on downgrade
Had: Downgrade of IPFS, not of Repo.

#### Command Output:
``` 
bertrand@computer:~$ ipfs-update --version
ipfs-update version 1.6.0

bertrand@computer:~$ ipfs-update version
v0.5.0-rc4

bertrand@computer:~$ sudo ipfs-update install 0.4.23 --allow-downgrade
fetching go-ipfs version v0.4.23
binary downloaded, verifying...
success! tests all passed.
stashing old binary
installing new binary to /usr/local/bin/ipfs
checking if repo migration is needed...
                                           ' <- EXPECTED A REPO REVERT MIGRATION HERE
Installation complete!

bertrand@computer:~$ ipfs daemon
Initializing daemon...
go-ipfs version: 0.4.23-
Repo version: 7
System version: amd64/linux
Golang version: go1.13.7

Error: Your programs version (7) is lower than your repos (9).
Please update ipfs to a version that supports the existing repo, or run
a migration in reverse.

See https://github.com/ipfs/fs-repo-migrations/blob/master/run.md for details.
```

**Comment by bertrandfalguiere** [comment]
related: #128, #127

**Comment by hsanjuan** [comment]
Hi @bertrandfalguiere ,

It seems you run your ipfs daemon  with your normal user : `$ ipfs daemon`.

But you are running `sudo ipfs-update install...`. By using sudo the 0.4.23 version of ipfs is getting installed to your root user, which probably had a different version of ipfs installed than 0.5.0-rc4 and did not need a migration.

Try downgrading without sudo.

For me things downgrades work as expected, and this is also covered in tests. Please re-open/comment if I missed base and you keep having problems.
