### ISSUE TITLE
failed update on private IPFS network

### ISSUE THREAD

**Issue by godcong** [ipfs/ipfs-update#132]
#### Version information:

ipfs-update version 1.6.0

#### Description:
my node was running on a private IPFS network.
if my `ipfs daemon` was running.
i run `ipfs-update install latest` command, the command line stops at the next line and does not move.
then if i stop the `daemon`, update will failed.

log:
```
>ipfs-update --verbose install  --allow-downgrade latest
  - fetching "/ipns/dist.ipfs.io/go-ipfs/versions"
  - using local ipfs daemon for transfer
```

**Comment by godcong** [comment]
so i change the step.
when the local was failed,then check the remote.

**Comment by sigma67** [comment]
This is quite confusing  behavior. Without the verbose option, it just seems as if the command was stuck and doesn't do anything. ipfs-update should notice that the local IPFS node is not able to retrieve the file (i.e. timeout) and instead use traditional http. 

I also believe the message ``using local ipfs daemon for transfer`` should be shown without the ``verbose`` option, but that's just my opinion.

**Comment by godcong** [comment]
> This is quite confusing behavior. Without the verbose option, it just seems as if the command was stuck and doesn't do anything. ipfs-update should notice that the local IPFS node is not able to retrieve the file (i.e. timeout) and instead use traditional http.
> 
> I also believe the message `using local ipfs daemon for transfer` should be shown without the `verbose` option, but that's just my opinion.

It should be that the cat is stuck
It can't execute because there is no timeout
I set the default timeout to 30minutes, maybe it can be shorter (5 minutes?)

**Comment by aschmahmann** [comment]
The issue seems to be:

https://github.com/ipfs/ipfs-update/blob/99d6de944a75da561824888e4c73d9d2d43c7174/util/utils.go#L103-L106

If `ipfs cat` fails then we just return instead of falling back to HTTP

**Comment by godcong** [comment]
> The issue seems to be:
> 
> https://github.com/ipfs/ipfs-update/blob/99d6de944a75da561824888e4c73d9d2d43c7174/util/utils.go#L103-L106
> 
> If `ipfs cat` fails then we just return instead of falling back to HTTP


Yes, and because there is no timeout, there will be a long pause

**Comment by sigma67** [comment]
30 minutes is definitely too long of a timeout.

**Comment by godcong** [comment]
Is 5 minutes or 3 minutes better?

**Comment by sigma67** [comment]
That's more reasonable, but the user should still be informed about it. Stalling for 3 minutes without notification what's going on is a no-no. Perhaps there's some way to display download progress? Or show a message "attempting download using the local IPFS node" ?
