### ISSUE TITLE
should install to system bin, not go

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs-update#19]
this should install to a system bin path, like `/usr/bin` or `/usr/local/bin`, depending on what the user's `$PATH` looks like (it may not have a `/usr/local/bin`).

```
> ipfs-update install v0.3.11
fetching ipfs version v0.3.11
binary downloaded, verifying...
success!
installing new binary to /home/jbenet/go/bin/ipfs
ERROR: Install failed:  error moving new binary into place: open /home/jbenet/go/bin/ipfs: no such file or directory
install failed, reverting changes...
ERROR: error moving new binary into place: open /home/jbenet/go/bin/ipfs: no such file or directory
```

I should not have to have go installed or configured to make this work.

**Comment by whyrusleeping** [comment]
it overwrites your currently installed go binary. If you have a `GOPATH` set, it uses that. Otherwise it will use `/usr/local/bin`
