### ISSUE TITLE
Fails with "multihash length inconsistent"

### ISSUE THREAD

**Issue by bergie** [ipfs/ipfs-update#25]
Running ipfs version 0.3.9-dev. ipfs-update installed via `go get -u github.com/ipfs/ipfs-update`

```
$ ipfs-update install 0.4.0-rc2
fetching ipfs version v0.4.0-rc2
install failed, reverting changes...
ERROR: cat: multihash length inconsistent: &{124  132 [104]} 
```

```
$  ipfs-update versions
ERROR: Failed to query versions:  cat: multihash length inconsistent: &{124  132 [104]}
```

**Comment by bergie** [comment]
It _seems_ to work with ipfs 0.3.11, though right now things are hanging. But that could be just bad WiFi.

**Comment by whyrusleeping** [comment]
This should be resolved. Was an issue with early versions of ipfs 0.3.*
