### ISSUE TITLE
ipfs-update fails to update ipfs to 0.4.0-dev

### ISSUE THREAD

**Issue by darkstar** [ipfs/ipfs-update#29]
Here's the transcript

```
darkstar@flonne:~$ go version
go version go1.6 linux/386
darkstar@flonne:~$ ipfs-update  version
v0.3.11-dev
darkstar@flonne:~$ ipfs-update  install v0.4.0-dev
fetching ipfs version v0.4.0-dev
binary downloaded, verifying...
success!
stashing old binary
installing new binary to /var/lib/go/bin/ipfs
checking if repo migration is needed...
  - Migration required
ERROR: Migration Failed:  # cd /var/lib/go/src/github.com/ipfs/fs-repo-migrations; git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'ipfs-1-to-2/golang-lru'
package github.com/ipfs/fs-repo-migrations: exit status 1
 exit status 1
install failed, reverting changes...
ERROR: # cd /var/lib/go/src/github.com/ipfs/fs-repo-migrations; git submodule update --init --recursive
No submodule mapping found in .gitmodules for path 'ipfs-1-to-2/golang-lru'
package github.com/ipfs/fs-repo-migrations: exit status 1
 exit status 1
```

I would be happy with just wiping and re-initializing/re-installing ipfs, but I have no idea where all those go-files and the other stuff is stored. I'm considering `rm -rf /var/lib/go` (since I have no other programs that use go) but I'm not sure if that'll break my whole installation

Any advice?

**Comment by zQueal** [comment]
I just experienced this. Seems like the `fs-repo-migrations` binary was not in my path and therefore `ipfs-update` was unable to use it for the actual migrations.

**Comment by whyrusleeping** [comment]
@zQueal were you using a newer version of `ipfs-update`? it should automagically download fs-repo-migrations and use it from the dists page.

**Comment by zQueal** [comment]
I believe I was--or at least I grabbed the default version from [dist.ipfs.io](https://ipfs.io/ipns/dist.ipfs.io/#ipfs-update).

**Comment by whyrusleeping** [comment]
This problem should be resolved. ipfs-update no longer tries to build migrations from source (which I believe was what was happening above).
