### ISSUE TITLE
Will this include https://github.com/ipfs/fs-repo-migrations ?

### ISSUE THREAD

**Issue by rht** [ipfs/ipfs-update#3]

**Comment by whyrusleeping** [comment]
I'm not quite sure how that flow is going to work yet. I think that the fs-repo-migrations could be fetched by this program, but they should be run by the user when starting their new ipfs daemon.

We want the migrations to happen automatically when you start the new version, unlike previously, where the user had to run it themselves.

**Comment by jbenet** [comment]
thanks for bringing this up @rht! @whyrusleeping and i discussed this in a hangout and we concluded that:

1. ipfs-update will run the fs-repo migration tool, both up, and down. will go up automatically, but will prompt before going down.
2. go-ipfs itself will not run the fs-repo migration tool automatically, but will prompt the user to do so if detecting mismatch, alerting of a version difference[0]. 

anything else decided @whyrusleeping ?

[0] this is important to avoid accidentally migrating repos when the user has multiple binaries in their system and accidentally uses the wrong version.

**Comment by whyrusleeping** [comment]
thats pretty much what i'm thinking too
