### ISSUE TITLE
Path Resolve error: no link named "go-ipfs_v0.4.2_linux-amd64.zip"

### ISSUE THREAD

**Issue by randoms** [ipfs/ipfs-update#37]
I got the following error when trying to upgrade to v0.4.2.

```
ERROR: fetching resource: 404 Not Found
install failed, reverting changes...
ERROR: 404 Not Found: Path Resolve error: no link named "go-ipfs_v0.4.2_linux-amd64.zip" under QmSqVhoY6pvX9wEPC6UE6r858NaZvQHfyFW7GUgepnRxR2 
```

I checked the dist page. It seems that the dist server not longer provides zip file.
![screenshot from 2016-06-29 11 24 07](https://cloud.githubusercontent.com/assets/3120090/16439530/0648d344-3dec-11e6-9225-6ed42b9dafac.png)

**Comment by whyrusleeping** [comment]
We switch to using `.tar.gz` on unixy systems. If you see this error with ipfs-update, please grab a newer version from https://dist.ipfs.io/#ipfs-update
