### ISSUE TITLE
Install of v0.4.3-dev fails: "invalid ipfs ref path"

### ISSUE THREAD

**Issue by wscott** [ipfs/ipfs-update#38]
I am currently running v0.4.2 installed via the ipfs-update tool and installed in `$HOME/gocode/bin/ipfs`.

I run `ipfs daemon` in one window and then in another window run this:

```
$ ipfs update  install v0.4.2
fetching go-ipfs version v0.4.2
binary downloaded, verifying...
success!
stashing old binary
installing new binary to /home/wscott/gocode/bin/ipfs
checking if repo migration is needed...

installation complete.
remember to restart your daemon before continuing
```

Works fine, but shouldn't have actually changed anything.  Just including that to demonstrate that it works.  Hit ^C in daemon window and wait for it to shutdown and then started it again.  Next I run this:

```
$ ipfs update  install v0.4.3-dev
fetching go-ipfs version v0.4.3-dev
binary downloaded, verifying...
success!
install failed, reverting changes...
ERROR: exit status 1: Error: invalid ipfs ref path
```

This time it fails.  Same thing happens when I run without a daemon running in the background.

**Comment by whyrusleeping** [comment]
This should work on the latest version of ipfs-update installing ipfs 0.4.4 or 0.4.5.

I think that during the 0.4.3 dev cycle when you tried this, there was an accidental breaking of the ipfs refs api which lead to the message you were seeing. The "success!" message was getting printed no matter what (this is fixed now) leading to some very confusing output.
