### ISSUE TITLE
Windows Issues

### ISSUE THREAD

**Issue by zQueal** [ipfs/ipfs-update#39]
Update flow on Windows is pretty broken.

Running `ipfs update install v0.4.3-rc1` yields;

```
binary downloaded, verifying...
install failed, reverting changes...
ERROR: error initializing with new binary: exec: "C:\\Users\\zqueal\\AppData\\Local\\Temp\\ipfs-update837744511\\ipfs-new": file does not exist:
```

Upon inspecting the folder, there is a zip with the new version in it. So I manually dropped it in my path. Come to find, however, that it's actually `0.4.3-dev` and not `v0.4.3-rc1` which is weird.

Running `ipfs daemon` after the "update" failed as well;

```
Initializing daemon...
Found old repo version, migrations need to be run.
Run migrations automatically? [y/N] y
  => checking for migrations binary...
  => usable migrations not found on system, fetching...
fetching url: https://ipfs.io/ipfs/QmUnvqDuRyfe7HJuiMMHv77AMUFnjGyAU28LFPeTYwGmFF/fs-repo-migrations/versions
fetching url: https://ipfs.io/ipfs/QmUnvqDuRyfe7HJuiMMHv77AMUFnjGyAU28LFPeTYwGmFF/fs-repo-migrations/v1.1.0/fs-repo-migrations_v1.1.0_windows-amd64.zip
Error: no migration binary found that supports version 4 - failed to check migrations version: exec: "C:\\Users\\zqueal\\AppData\\Local\\Temp\\go-ipfs-migrate672150123\\fs-repo-migrations": file does not exist
```

From here I couldn't get the migrations to happen*. So I ended up removing my `.ipfs` repo and `ipfs init` again.

`ipfs-update fetch` seems to grab the linux version, and not the windows version.

---

\* It seems I was unable to get migrations to happen because I didn't have the `fs-repo-migrations.exe` in my path.

**Comment by Azulan** [comment]
I've been having the same problem.

**Comment by hsanjuan** [comment]
reopen if still happening
