### ISSUE TITLE
Code Review up to now

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs-update#4]
## Tested it out-- seems to work! :+1: 

- nice command help
- minor testing, seems to work well :+1:  :fireworks: :clap:
- clear output tells the user what's going on
- nice reverting ([with interactive select!](https://38.media.tumblr.com/947ceaa2cef127f0481b388f8d9a9551/tumblr_mvq95tg9Kj1snx6rjo2_400.gif)) :sunglasses: 
- nice `ipfs-update versions` output

![](https://ipfs.io/ipfs/QmRfndgFK4XWHus1yBwbpzpsuYSLftCsJ2KptYPrMf4LTj/shia-clap.gif)
![](http://www.gifbin.com/bin/012014/1391200591_daft_punk_grammy_clap.gif)

## Things to Fix

- [x] command help could be more user friendly: no idea what to feed it here:

  ```
  ./ipfs-update revert --help
  NAME:
     ./ipfs-update revert - revert to previously installed version of ipfs

  USAGE:
     ./ipfs-update revert [arguments...]

  DESCRIPTION:
     revert will check if a previous update left a stashed
  binary and overwrite the current ipfs binary with it.
  ```

- [x] use `v<num>` or `<num>`, be consistent:

    ```
    > ./ipfs-update versions
    v0.3.2
    v0.3.4
    v0.3.5
    v0.3.6
    v0.3.7
    v0.3.8
    v0.3.9
    > ./ipfs-update version
    0.3.9
    ```

- [x] improve description of `stash` cmd, not clear what it would be used for.
- [x] separate `testnew.go` into own subpkg -- https://github.com/ipfs/ipfs-update/blob/b4d672f8551bb17e8f84d19b35cfbf2b82a9f400/testnew.go
- [ ] separate the "update bundle" formatting parts into a subpkg (versions.go)
- [x] use `localApiUrl` const for url https://github.com/ipfs/ipfs-update/blob/b4d672f8551bb17e8f84d19b35cfbf2b82a9f400/versions.go#L31
- [ ] port is configurable... https://github.com/ipfs/ipfs-update/blob/b4d672f8551bb17e8f84d19b35cfbf2b82a9f400/versions.go#L31
  - [ ] read `$repo/api` file (respect $IPFS_PATH)
  - [ ] respect `--api` flag
- [ ] should bound the `httpFetch` `resp.Body` reader with a limited reader (like at most {4MB, 8MB} or something) -- https://github.com/ipfs/ipfs-update/blob/b4d672f8551bb17e8f84d19b35cfbf2b82a9f400/utils.go#L24 to avoid hosing the local client's memory if there's a malicious remote host.
- [ ] Decompose into logical units! https://github.com/ipfs/ipfs-update/blob/b4d672f8551bb17e8f84d19b35cfbf2b82a9f400/install.go#L17 -- long sequences of tangential instructions ARE NOT easy to follow. I had to break it up into this: https://gist.github.com/jbenet/aa51fce4fb271f92070e just to check everything made sense. Use that or something even better.
- [ ] should say "error reverting" -- https://github.com/ipfs/ipfs-update/blob/b4d672f8551bb17e8f84d19b35cfbf2b82a9f400/revert.go#L20
- [ ] Give user directions on what to do now: https://github.com/ipfs/ipfs-update/blob/b4d672f8551bb17e8f84d19b35cfbf2b82a9f400/revert.go#L22 -- maybe like

  ```
  maybe try: mv $stashpath $binpath
  ```
  Otherwise, this tool leaves users totally in the dust. "my old binary is in X, ok? what does that mean? what should i do?"
- [ ] mixing your stump thing with `fmt.Fprintf` !? -- https://github.com/ipfs/ipfs-update/blob/b4d672f8551bb17e8f84d19b35cfbf2b82a9f400/revert.go#L56 -- great now changing the logger will fail to catch these.
- [ ] if going to allow overriding stdio elsewhere, make this a variable reader too, not os.Stdio -- https://github.com/ipfs/ipfs-update/blob/b4d672f8551bb17e8f84d19b35cfbf2b82a9f400/revert.go#L61
- [ ] repeat `"(0 to exit)"` here -- https://github.com/ipfs/ipfs-update/blob/b4d672f8551bb17e8f84d19b35cfbf2b82a9f400/revert.go#L68

- [ ] can the "VERSION" and "AUTHORS" parts be removed from standard `--help` output? i think it's distracting to the average user. or if not, then maybe as one subtle line at the end? 

    ```
    ipfs-update version <version>, by <authors>
    ```

- [ ] The habit of writing out to the user from the bowels of the code is very bad. It makes me never want to touch this code, as any meaningful refactor could have unintended serious impact in the flow of the UX.

- [ ] bad error -- handle errors better

  ```
  ./ipfs-update install 0.3.8
  installing ipfs version 0.3.8
  fetching 0.3.8 binary...
  ERROR: no link named "0.3.8" under QmctgsD3G5MrvUcuVAZ6tVXP2c2pkgsEsqT85gQaTcfGjw
  ```

- [ ] silently correct inputs not specifying the `v` (or clearly handle this error specially, by prompting the user to add it)

- [ ] [none of this is tested](http://i.imgur.com/EPK2WvB.jpg)

#### but needs lots of testing before i would be comfortable shipping this to users in a "this is the recommended upgrade path" state.

**Comment by jbenet** [comment]
any ideas on how to test this stuff? maybe a sharness suite that upgrades through all the versions runs tests on each version, does stuff and then verifies everything is still fine? like have some workloads (mix of adding + pinning/unpinning + gcing  a lot of things) and then have the expected output, upgrade through and check everything is still the same. particularly important with the pinset changes for the migration. this could be a test for both migrations and ipfs-update that make sure everything is solid across version changes.

cc @chriscool thoughts?

**Comment by whyrusleeping** [comment]
> mixing your stump thing with fmt.Fprintf !? -- https://github.com/ipfs/ipfs-update/blob/b4d672f8551bb17e8f84d19b35cfbf2b82a9f400/revert.go#L56 -- great now changing the logger will fail to catch these.

I'm trying to differentiate between 'output' and 'logs', Printf and friends are used for program output (i.e. `ipfs-update version > myversion`)

**Comment by whyrusleeping** [comment]
> but needs lots of testing before i would be comfortable shipping this to users in a "this is the recommended upgrade path" state.

Fortunately this doesnt need to be a 'recommended' upgrade path until 0.4.0, we can ship 0.3.10 and still not "recommend" it as the primary upgrade path.

**Comment by jbenet** [comment]
@whyrusleeping ok sounds good. we'll need thorough testing by 0.4.0 though

**Comment by whyrusleeping** [comment]
@jbenet agreed. I'm hoping @chriscool has good ideas on testing this nicely, theres a good number of moving parts involved.

**Comment by chriscool** [comment]
Ok, I will have a look at testing it soon...

**Comment by whyrusleeping** [comment]
youre the bestest ever

**Comment by chriscool** [comment]
@whyrusleeping thanks!

Please take a look: https://github.com/ipfs/ipfs-update/pull/5
