### ISSUE TITLE
Install Failed. ERROR: Post

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs-update#40]
```
> ipfs-update install latest
fetching ipfs version v0.4.3-rc1
install failed, reverting changes...
ERROR: Post http://127.0.0.1:5001/api/v0/cat?arg=%2Fipns%2Fdist.ipfs.io%2Fgo-ipfs%2Fv0.4.3-rc1%2Fgo-ipfs_v0.4.3-rc1_linux-amd64.tar.gz&encoding=json&stream-channels=true: EOF
```

I have:
- a daemon running (0.4.2)
- want to upgrade to 0.4.3-rc1

problem:
- the error above is not indicative of the problem, or helpful
- the error above leaves me at a loss of what to do.
- not clear why it failed.

**Comment by jbenet** [comment]
More:

```
jbenet @ gundabad : ~ % sudo service ipfs stop
[sudo] password for jbenet:
ipfs stop/waiting
jbenet @ gundabad : ~ % ipfs-update install latest
fetching ipfs version v0.4.3-rc1
binary downloaded, verifying...
install failed, reverting changes...
ERROR: version didnt match
jbenet @ gundabad : ~ % ipfs version
ipfs version 0.4.2
```

**Comment by imars** [comment]
I'm having the same error with v0.4.5-pre2

imars:~ me$ ipfs-update install latest
fetching go-ipfs version v0.4.5-pre2
binary downloaded, verifying...
install failed, reverting changes...
ERROR: version didnt match

**Comment by hsanjuan** [comment]
@imars running the lastest ipfs-update?

**Comment by imars** [comment]
@hsanjuan It's version 1.5.0 with ipfs at v0.4.4. I'm on macOS 10.12.2.

**Comment by imars** [comment]
@hsanjuan ipfs-update is now working for me with the latest install of ipfs at 0.4.5-rc1.

**Comment by hsanjuan** [comment]
@imars :/ weird... you should see `rc2` too? does it work also?

**Comment by imars** [comment]
@hsanjuan It's back to the same failure while trying to get latest.

$ ipfs-update versions
..
v0.4.3
sharding-pre
v0.4.4
v0.4.5

$ ipfs-update install latest
fetching go-ipfs version v0.4.5
binary downloaded, verifying...
install failed, reverting changes...
ERROR: version didnt match

**Comment by whyrusleeping** [comment]
@imars could you run it in verbose mode: `ipfs-update --verbose install latest` ?

That should help provide a bit more info. Also trying: `ipfs-update fetch latest` should download the latest binary for you, and then you can try using it yourself and see if its broken for some reason and report that back for us.

**Comment by imars** [comment]
@whyrusleeping The /api directory is in fact missing, however, I've tested ipfs-v0.4.6 and it's working fine.

> ipfs-update --verbose install latest
  - fetching "/ipns/dist.ipfs.io/go-ipfs/versions"
fetching url: https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/versions
daemon check failed: open /Users/imars/.ipfs/api: no such file or directory
fetching go-ipfs version v0.4.6
  - using GOOS=darwin and GOARCH=amd64
  - fetching "/ipns/dist.ipfs.io/go-ipfs/v0.4.6/go-ipfs_v0.4.6_darwin-amd64.tar.gz"
fetching url: https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/v0.4.6/go-ipfs_v0.4.6_darwin-amd64.tar.gz
  - writing to /var/folders/m2/jym7f8m10j9fy4rcqjbbl_5w0000gn/T/ipfs-update092490160/go-ipfs_v0.4.6_darwin-amd64.tar.gz
  - extracting binary to tempdir:  /var/folders/m2/jym7f8m10j9fy4rcqjbbl_5w0000gn/T/ipfs-update925166677/ipfs-new
binary downloaded, verifying...
  - running init in '/Users/imars/.ipfs/update-staging/test929253711' with new binary
  - running: [/var/folders/m2/jym7f8m10j9fy4rcqjbbl_5w0000gn/T/ipfs-update925166677/ipfs-new init]
  - checking new binary outputs correct version
  - running: [/var/folders/m2/jym7f8m10j9fy4rcqjbbl_5w0000gn/T/ipfs-update925166677/ipfs-new version]
install failed, reverting changes...
ERROR: version didnt match

**Comment by whyrusleeping** [comment]
@imars Could you try using ipfs-update 1.5.2? This may have been resolved

**Comment by imars** [comment]
@whyrusleeping I finally removed ipfs and ipfs-update and then installed the latest versions, everything seems to be working now.

Thank you all for your assistance.

**Comment by whyrusleeping** [comment]
@imars Thanks for reporting the issue and following up :)

Please do report anything else you run into
