### ISSUE TITLE
Don't use ~/go/bin

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs-update#43]
So apparently this tool installs `ipfs` into $GOPATH/bin. this tool is meant for people _without_ go. this should use some other standard bin location.

**Comment by whyrusleeping** [comment]
@jbenet it uses that path *if* it exists.

**Comment by jbenet** [comment]
Ah, now I understand how it works: it uses $(which ipfs) -- fine.

Closed. (Seeing if github will answer cmds by mail)
