### ISSUE TITLE
ipfs-update windows error

### ISSUE THREAD

**Issue by edsilv** [ipfs/ipfs-update#46]
```
$ ipfs-update install v0.4.4
fetching go-ipfs version v0.4.4
binary downloaded, verifying...
install failed, reverting changes...
ERROR: error initializing with new binary: exec: "C:\\Users\\edsilv\\AppData\\Local\\Temp\\ipfs-update648285215\\ipfs-new": file does not exist:
```

`ipfs version` is 0.4.2

on windows 10 x64

**Comment by whyrusleeping** [comment]
Sorry for taking so long to respond to this.

I have not been able to do testing on windows, But i will start doing this soon (my new laptop has windows as a second partition instead of OSX) and report back.

In the meantime, and for others experiencing this problem, You could try the `--no-check` flag which skips the small series of tests that ipfs-update runs on the new binaries it downloads

**Comment by iav** [comment]
I run
`ipfs-update.exe install --no-check 0.4.8` on Windows 7 x64.
It download ipfs binary and placed it into correct location – but without .exe extension. It means file unstartable on windows. Then I rename file ipfs into ipfs.exe – and it run, and show me 0.4.8 version.

**Comment by Azulan** [comment]
I have the same problem. Probably related to #39.

**Comment by akavel** [comment]
Similar situation:

```
C:\dnload\ipfs-etc\ipfs-update>ipfs-update.exe -v
ipfs-update.exe version 1.5.1

C:\dnload\ipfs-etc\ipfs-update>ipfs-update.exe install latest
fetching go-ipfs version v0.4.13
binary downloaded, verifying...
install failed, reverting changes...
error initializing with new binary: exec: "C:\\Users\\Mateusz\\AppData\\Local\\Temp\\ipfs-update391963503\\ipfs-new": file does not exist:

C:\dnload\ipfs-etc\ipfs-update>ipfs-update.exe install --no-check latest
fetching go-ipfs version v0.4.13
skipping tests since '--no-check' was passed
install failed, reverting changes...
could not find good install location
```

hmh, not sure what the last message about "good install location" means :(
