### ISSUE TITLE
Unable to update to v0.4.4

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/ipfs-update#47]
I am having some issues updating this.

I wanted to update `go-ipfs`. So, I found out what version I had - `v0.4.2`. Then, I went to ipfs/go-ipfs, and looked at the update section. It told me to go to `ipfs-update`. I already have that installed, so I ran it. When I ran `$ ipfs-update versions`, it showed me up to `v0.4.2`. This, I think, means that I have those versions installed - but that wouldn't help me update it, as I don't know the current version. So, I went to dist.ipfs.io, and saw that there is a version v0.4.4.

```
$  ipfs update install v0.4.4
fetching ipfs version v0.4.4
install failed, reverting changes...
ERROR: no link named "v0.4.4" under QmXaJQK4s9MK79nayF6XCUvCzpweXXTxY5ZtSsCoZ2jTAq
```

What am I doing wrong here?

**Comment by hsanjuan** [comment]
Hummm, I would try to update ipfs-update ... it should show up to v0.4.4 even if it's not installed. Somehow it is getting the list of available versions from an old hash:

```
> ipfs-update --verbose versions
  - fetching "/ipns/dist.ipfs.io/go-ipfs/versions"
fetching url: https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/versions
v0.3.2
v0.3.4
v0.3.5
v0.3.6
v0.3.7
v0.3.8
v0.3.9
v0.3.10
v0.3.11
v0.4.0
v0.4.1
v0.4.2
floodsub-2
v0.4.3
v0.4.4
sharding-pre
```

**Comment by RichardLitt** [comment]
Is the only way to update ipfs-update to go to dist.ipfs.io? I've done that now, and confirmed that updating the newest ipfs-update seems to work. Updating ipfs-update to update ipfs seems like poor UX, though.

**Comment by stadja** [comment]
I experience the same here:

```
> ipfs-update install 0.4.4
fetching go-ipfs version v0.4.4
binary downloaded, verifying...
success!
stashing old binary
installing new binary to /srv/Ubuntu_backup/golang/bin/ipfs
checking if repo migration is needed...
  - Migration required
fetching fs-repo-migrations version v1.1.1
ERROR: Migration Failed:  no known migration supports version 4
install failed, reverting changes...
ERROR: no known migration supports version 4
You have new mail.
```

**Comment by whyrusleeping** [comment]
Early versions of ipfs-update had hard-coded the hash of the distributions page they were pulling information from. Newer versions use `/ipns/dist.ipfs.io`.

If you wish to use a specific distibutions page ref, you can do `ipfs-update --distpath=/ipfs/QmFooBar install v0.4.5`. But in general, you shouldnt need to do so.
