### ISSUE TITLE
unable to update to ipfs v0.4.5-pre1

### ISSUE THREAD

**Issue by Kuurusch** [ipfs/ipfs-update#48]
Hallo, I tried to update ipfs over ipfs-update (v1.4.0) but it sais, "version didnt match".
Did I miss something or is there a problem?

Thanks for help!

**Comment by whyrusleeping** [comment]
This is because we didnt change the coded version on the ipfs binary. You might try passing `--no-check` to the install command. If that doesnt help i'll have to add some extra checks to be okay with pre-release versions

**Comment by whyrusleeping** [comment]
@Kuurusch Could you try building ipfs-update from source (latest master) and see if it resolves the problem?

**Comment by Kuurusch** [comment]
Ah thanks a lot, --no-check worked!

**Comment by machawk1** [comment]
I ran into this same issue. ipfs-update "found" v0.4.5-pre1 after I updated ipfs-update via `go get -u github.com/ipfs/ipfs-update` then re-ran `ipfs-update install 0.4.5-pre1`.
