### ISSUE TITLE
`sync` feature

### ISSUE THREAD

**Issue by victorb** [ipfs/ipfs-update#49]
Inspired by concourse's `fly` cli, a `sync` feature (https://concourse.ci/fly-sync.html) that once run against the API (in this case, a ipfs daemon API) would sync the version of the cli to match the version on the API.

```
$ ipfs id
Incompatible API version!
$ ipfs-update sync /ip4/127.0.0.1/tcp/5001
Checking version of API...
Got version 0.4.3, downloading the right IPFS version
Downloaded! 
$ ipfs id
{
	"ID": "QmZ8pJ4vNP4BSH",
	"PublicKey": "CAASpgIwggEiMA0QOevfKUQWkPDCqyh3hlcCSyUTAgMBAAE=",
	"Addresses": null,
	"AgentVersion": "go-libp2p/3.3.4",
	"ProtocolVersion": "ipfs/0.1.0"
}
```

**Comment by VictorBjelkholm** [comment]
We could also print out a message to use `ipfs-update sync` if there is an error like what happen here: https://github.com/ipfs/go-ipfs/issues/3452

**Comment by whyrusleeping** [comment]
This is a pretty cool idea, :+1:
