### ISSUE TITLE
ERROR while updating to 0.4.6-rc1

### ISSUE THREAD

**Issue by Mossfeldt** [ipfs/ipfs-update#56]
ipfs update install v0.4.6-rc1
fetching go-ipfs version v0.4.6-rc1
binary downloaded, verifying...
install failed, reverting changes...
ERROR: version didnt match

**Comment by whyrusleeping** [comment]
Try running with --no-check. Very odd to be seeing this now, i'm quite certain we updated the version for the release candidate (as was the cause of this problem in the past). I'll verify

**Comment by Mossfeldt** [comment]
--no-check did the trick.

ipfs update install v0.4.6-rc1 --no-
check
fetching go-ipfs version v0.4.6-rc1
skipping tests since '--no-check' was passed
stashing old binary
installing new binary to /usr/local/bin/ipfs
checking if repo migration is needed...

Installation complete!

Den 23 feb. 2017 9:50 fm skrev "Jeromy Johnson" <notifications@github.com>:

**Comment by Kubuxu** [comment]
Can you send `ipfs-update --version`?

**Comment by Mossfeldt** [comment]
Ipfs-update version 1.5.0

**Comment by Mossfeldt** [comment]
Don't know if its related but
 ipfs id                     
api version mismatch (/go-ipfs/0.4.5/ != /go-ipfs
/0.4.6-rc1/)

**Comment by Kubuxu** [comment]
you have to restart the daemon after update

**Comment by Mossfeldt** [comment]
Forgot that. Thnx for the reminder. Silver the api mismatch.

**Comment by Mossfeldt** [comment]
Tested on one of my other nodes 
ipfs-update install v0.4.6-rc1
fetching go-ipfs version v0.4.6-rc1
binary downloaded, verifying...
install failed, reverting changes...
ERROR: version didnt match 

ipfs-update install v0.4.6-rc1 **--no-check**
fetching go-ipfs version v0.4.6-rc1
skipping tests since '--no-check' was passed
stashing old binary
installing new binary to /usr/local/bin/ipfs
checking if repo migration is needed...

Installation complete!

**Comment by Kubuxu** [comment]
It is interesting. I will experiment.

**Comment by jbenet** [comment]
I get the same thing on v0.4.5 too.

**Comment by Kubuxu** [comment]
Ahh, this was already fixed. I will increase version number to 1.5.1.
