### ISSUE TITLE
`ipfs-update --version` is wrong

### ISSUE THREAD

**Issue by jbenet** [ipfs/ipfs-update#58]
I'm supposed to have 1.5.2 and it gives me 

```
./ipfs-update --version
ipfs-update version 1.5.1
```

:( 

TODOs:
- [ ] fix the version :)
- [ ] add a test so this never happens again :)

**Comment by gowthamgts** [comment]
As per this [line](https://github.com/ipfs/ipfs-update/blob/bdd7a6d806adddcf84c5c7bf5d77c57643061972/config/config.go#L7), the current version is 1.5.1.  Isn't this the expected behaviour?

**Comment by Stebalien** [comment]
@gowthamgts a new version was tagged without updating that. The latest version is 1.5.2.

**Comment by Stebalien** [comment]
Unfortunately, I'm not sure adding a test is doable (cat do PRs for git tags).
