### ISSUE TITLE
Try $HOME/.local/bin instead of or as well as $HOME/bin for installing

### ISSUE THREAD

**Issue by octylFractal** [ipfs/ipfs-update#61]
Most people use `.local/bin` instead of `bin` for their personal binaries.

**Comment by whyrusleeping** [comment]
@kenzierocks Ah, right. I wonder if theres a more general rule i could use than hardcoding some options here

**Comment by kenzierocks** [comment]
The best rule I can think of is the location of `ipfs-update`. I assume most people would want the `ipfs` binaries in the same place. It might also be good to have a command-line switch like `--prefix` to allow the user to set it themselves.

**Comment by Stebalien** [comment]
Fixed. We now try `~/.local/bin` (if it's in the PATH and exists).
