### ISSUE TITLE
Windows new window popup and exit

### ISSUE THREAD

**Issue by techtonik** [ipfs/ipfs-update#63]
`ipfs-update.exe` asks for permissions, then runs in popup window and exits. Output redirection doesn't work, so I can't even read the help.

**Comment by Ilias48rus** [comment]
Same here, don't know if it require some special initialization protocol, but i would expect the .exe to just open a working command-line window :)
![viZmisZipfsUpdate](https://user-images.githubusercontent.com/13949704/64271664-63c49a00-cf46-11e9-9ca0-ed4d2666e9f2.gif)

**Comment by Stebalien** [comment]
ipfs-update is a non-interactive command line utility. You'll need to open a terminal _first_ then run it from there.

If you're using Windows, I recommend [ipfs-desktop](https://github.com/ipfs-shipyard/ipfs-desktop). It'll handle all this for you.

**Comment by Ilias48rus** [comment]
@Stebalien , thanks for the answer, i've already found the ipfsD (trough issue on the go-ipfs), so the official utilities are like a set variables with functions .

**Comment by Stebalien** [comment]
I agree. There's a documentation issue (https://github.com/ipfs/docs/issues/188) for fixing this.
