### ISSUE TITLE
Cannot build with Go 1.7 due to dependency

### ISSUE THREAD

**Issue by lsc36** [ipfs/ipfs-update#65]
Not familiar with Go, but it seems that `sort.Slice` is being used in
`github.com/libp2p/go-libp2p-connmgr`
depended by `github.com/libp2p/go-libp2p-host`
depended by `github.com/libp2p/go-floodsub`
depended by `github.com/ipfs/go-ipfs-api`,
which requires Go 1.8+. Either pin down to a previous version (if possible) or update README?

**Comment by Stebalien** [comment]
Thanks!
