### ISSUE TITLE
ipfs-update distribution binary gets filtered

### ISSUE THREAD

**Issue by puilp0502** [ipfs/ipfs-update#69]
I'm using Chrome 60.0.3112.113, and Windows amd64 binary cannot be downloaded, as shown in this screenshot.
![image](https://user-images.githubusercontent.com/5106603/30333105-175397e2-9817-11e7-9bb1-745a13db4b5a.png)
(That's just saying `This file is dangerous and we blocked it`)

**Comment by lgierth** [comment]
Thanks for bringing this up, we're working on fixing it

**Comment by lgierth** [comment]
This should be fixed now - thanks!

**Comment by VictorBjelkholm** [comment]
While this has been fixed and we got a response from Google that they are removing the warning, it might take a few hours before it's propagated everywhere. As of right now, the warning still seems to appear but will disappear soon.
