### ISSUE TITLE
Timeouts with v0.3.8 and v0.3.7

### ISSUE THREAD

**Issue by chriscool** [ipfs/ipfs-update#7]
I get:

```
#  sharness/bin/ipfs-update install v0.3.8
installing ipfs version v0.3.8
ERROR: fetching resource: 408 Request Timeout
install failed, reverting changes...
ERROR: 408 Request Timeout: Path Resolve error: context deadline exceeded

#  sharness/bin/ipfs-update install v0.3.7
installing ipfs version v0.3.7
ERROR: fetching resource: 408 Request Timeout
install failed, reverting changes...
ERROR: 408 Request Timeout: Path Resolve error: context deadline exceeded

#  sharness/bin/ipfs-update install v0.3.10
installing ipfs version v0.3.10
ERROR: fetching resource: 404 Not Found
install failed, reverting changes...
ERROR: 404 Not Found: Path Resolve error: no link named "v0.3.10" under QmctgsD3G5MrvUcuVAZ6tVXP2c2pkgsEsqT85gQaTcfGjw 

```

So basically I can only write tests using v0.3.9.

**Comment by whyrusleeping** [comment]
0.3.10 hasnt been pushed out to the distributions yet (ipfs update pulls from a build of 'dist.ipfs.io'). The other ones should be back up now, I thought I had them pinned, but it seems i was wrong.

**Comment by chriscool** [comment]
Great, thanks!

**Comment by chriscool** [comment]
And what about 0.4.0 by the way?

**Comment by jbenet** [comment]
getting `Path Resolve error: context deadline exceeded` is so painful for users. it's like ["wat?"](https://s-media-cache-ak0.pinimg.com/736x/30/b1/6e/30b16eaa7d85f22dbe976c70fe6d4ec2.jpg)

**Comment by chriscool** [comment]
Yeah I still get that too for v0.3.7:

```
#  sharness/bin/ipfs-update install v0.3.7
installing ipfs version v0.3.7
ERROR: fetching resource: 408 Request Timeout
install failed, reverting changes...
ERROR: 408 Request Timeout: Path Resolve error: context deadline exceeded
```

But it's working for v0.3.8:

```
#  sharness/bin/ipfs-update install v0.3.8
installing ipfs version v0.3.8
binary downloaded, verifying...
success!
installing new binary to /usr/local/bin/ipfs

installation complete.
```

**Comment by chriscool** [comment]
Also installing the same version twice fails:

```
root@3416e74c98e9:/mnt# sharness/bin/ipfs-update install v0.3.8
installing ipfs version v0.3.8
binary downloaded, verifying...
success!
stashing old binary
installing new binary to /usr/local/bin/ipfs/ipfs
ERROR: Install failed:  error moving new binary into place: open /usr/local/bin/ipfs/ipfs: no such file or directory
install failed, reverting changes...
Error reverting
failed to replace binary after install fail:  open /usr/local/bin/ipfs/ipfs: no such file or directory
sorry :(
your old ipfs binary should still be located at:  /root/.ipfs/old-bin/ipfs-v0.3.8
try: `mv "/root/.ipfs/old-bin/ipfs-v0.3.8" "/usr/local/bin/ipfs/ipfs"`
ERROR: error moving new binary into place: open /usr/local/bin/ipfs/ipfs: no such file or directory 
```

**Comment by chriscool** [comment]
Actually I also get the above when installing v0.3.8 when v0.3.9 is already installed.

**Comment by jbenet** [comment]
I have a new distributions root:

- /ipfs/QmeEVmRTDX2c9zjPtjHJG6GidrFL7NjqEqP1Q4am6sLfif
- see it: https://ipfs.io/ipfs/QmeEVmRTDX2c9zjPtjHJG6GidrFL7NjqEqP1Q4am6sLfif
- includes `0.3.10` and `0.4.0-dev`: https://ipfs.io/ipfs/QmeEVmRTDX2c9zjPtjHJG6GidrFL7NjqEqP1Q4am6sLfif/go-ipfs
- it has not been published to `update.ipfs.io` so this tool wont find it yet -- track https://github.com/ipfs/infrastructure/issues/139

@chriscool test 0.4.0  as `0.4.0-dev` for now. this one will be removed once we ship proper `0.4.0`.

**Comment by harlantwood** [comment]
When I click on changelog ( https://ipfs.io/ipfs/QmeEVmRTDX2c9zjPtjHJG6GidrFL7NjqEqP1Q4am6sLfif/go-ipfs/v0.3.10/changelog )

I get `Path Resolve error: no link named "changelog" under QmRU3WnKuzyEbyEd7Y8L4Lfhh7sWX68axtqJTkgpc9k3um`

**Comment by whyrusleeping** [comment]
@jbenet did you pin that hash?

**Comment by jbenet** [comment]
There's no changelog in that dir:
https://ipfs.io/ipfs/QmeEVmRTDX2c9zjPtjHJG6GidrFL7NjqEqP1Q4am6sLfif/go-ipfs/v0.3.10/
we may not be collecting the changelog yet! -- bug for distributions.ipfs.io
