### ISSUE TITLE
arm64 build

### ISSUE THREAD

**Issue by renich** [ipfs/ipfs-update#76]
It would be awesome to have an arm64 build.

**Comment by NatoBoram** [comment]
You can compile it yourself!

```Bash
sudo apt install golang-go
go get -u -v -fix github.com/ipfs/ipfs-update
go install github.com/ipfs/ipfs-update
```

The only thing that is truly missing is a build for `go-ipfs` in arm64.

**Comment by Kubuxu** [comment]
I've created: https://github.com/ipfs/distributions/issues/175

**Comment by Kubuxu** [comment]
Closing this for now, please use that issue to track progress.
