### ISSUE TITLE
Error: ipfs-update not installed.

### ISSUE THREAD

**Issue by parfenov** [ipfs/ipfs-update#77]
hi guys, what should I try to get IPFS updated ?

>> ipfs version
ipfs version 0.4.0

>>ipfs update
Error: ipfs-update not installed.

**Comment by renatoathaydes** [comment]
`ipfs update` tries to call `ipfs-update` and you seem to not have it installed.

Try installing [ipfs-update](https://github.com/ipfs/ipfs-update).

**Comment by AnandWalvekar** [comment]
Hi @renatoathaydes 
"go get -u github.com/ipfs/ipfs-update" command on terminal returns after a while but same error keeps showing upon "ipfs update" and not sure where "ipfs-update" got installed

**Comment by renatoathaydes** [comment]
`go get` always installs programs at `$GOPATH/bin`, usually `/usr/local/go/bin`, or `~/go/bin`.

See https://github.com/golang/go/wiki/GOPATH.
