### ISSUE TITLE
ipfs update install should install the latest version with no version specified

### ISSUE THREAD

**Issue by erkinalp** [ipfs/ipfs-update#79]
#### Description: Currently ipfs update install requires a version to be specified.
ipfs update install with no versions should install the latest version instead as this is the most common use case.

**Comment by gowthamgts** [comment]
Can agree, today I was feeling the same. This should reduce two steps (listing and installing) into a single command.

**Comment by gowthamgts** [comment]
@Stebalien how is this different from `ipfs-update fetch`?

**Comment by erkinalp** [comment]
`ipfs-update fetch` does not install.

**Comment by gowthamgts** [comment]
I was on ipfs `v0.4.13` and `ipfs-update fetch` installed `v0.4.14` perfectly fine. Here's the output:
```
gts:~$ ipfs-update fetch
fetching go-ipfs version v0.4.14
gts:~$ ipfs-update fetch
ERROR: file named "ipfs-v0.4.14" already exists
```

**Comment by steverecio** [comment]
I was trying to run `ipfs update install latest` and while it seemed to pick up the latest version, it failed to acquire the `repo.lock` file. However, running `ipfs update install v0.4.14` ran fine and installed the latest version.

Is something broken here or is this expected behavior?

**Comment by Stebalien** [comment]
> I was trying to run ipfs update install latest and while it seemed to pick up the latest version, it failed to acquire the repo.lock file. However, running ipfs update install v0.4.14 ran fine and installed the latest version.

This is a bug in the *current* version where it locks the repo before installing. Unfortunately, it then tries to run a repo migration which *also* needs to lock the repo. The solution is to manually run `ipfs-update install latest` (note the `-`).

---

You're right, this is looks like a documentation fix.

**Comment by ThomasFreedman** [comment]
So why is this issue still open after more than a year, if only a doc fix?

I agree with the OP, the latest should be default if no version is provided.

I seem to always run into trouble with ipfs-update. I use it ever other month or so and every time my install script fails when I use ipfs-update to install ipfs.

I've seen this error before as well: **could not find good install location** My workaround last time was to copy the program from where the tests were I want it to live (under my own go folder).

This time I'm using latest golang version (1.13) on arm61 arch (Raspberry Pi 3 / Raspbian 9.1). ipfs-update successfully downloads and reports: **success! tests all passed.**, followed by **install failed, reverting changes...** then **could not find good install location**.

**Comment by parkan** [comment]
documented in https://github.com/ipfs/ipfs-update/commit/3b9a359a443d0c33a8c7452d2d92023b341af8af though agree it could be a bit clearer
