### ISSUE TITLE
Censored in China

### ISSUE THREAD

**Issue by buckle2000** [ipfs/ipfs-update#80]
The site `https://ipfs.io` and `https://dist.ipfs.io` are fully censored by the GFW. Is there a way to update ipfs via IPFS?

**Comment by Stebalien** [comment]
Yes. Is it still possible to lookup dist.ipfs.io via DNS? If so, you should be able to fetch IPFS from `/ipns/dist.ipfs.io/`.

Warning! DNS is *not* secure. At the moment, you can download IPFS *directly* from /ipfs/QmczXtuCDYuMN5i4X7EYM658wraGeNjBUQQMtkDNfYPmx5 (securely).

However, none of these solutions will help with ipfs-update.

**Comment by buckle2000** [comment]
Every domain blocked by the GFW also has its DNS polluted.

**Comment by buckle2000** [comment]
Can ipfs-update integrate `ipget`? In that way, ipfs-update can download ipfs from `/ipns/<hash>` even if DNS and HTTP(S) are censored.

**Comment by Stebalien** [comment]
That won't help as, as far as I know, we don't use IPNS for dists. However, we really should.

Note: We use dnslink which uses the `/ipns` prefix but that's not actually IPNS. Yes, this is really confusing.

@lgierth how hard would it be to publish IPNS records for dists.ipfs.io?

**Comment by buckle2000** [comment]
How about we change `/ipns/<domain name>` into `/dns/<domain name>`?

**Comment by nothingismagick** [comment]
There might also be another problem here: 

https://github.com/ipfs/ipfs-update/blob/4d18c479cdb739cb6fb53063041d589cb87a3586/util/utils.go#L22

**Comment by zhjgit** [comment]
ipfs upgrade is wall, is there a solution at present?

**Comment by Stebalien** [comment]
At the moment, you can manually download releases from github: https://github.com/ipfs/go-ipfs/releases/tag/v0.4.22. If you already _have_ IPFS installed and running, it looks like `ipfs-update` will use that. Unfortunately, that still relies on DNS.

For the latest release, you can run:

```bash
ipfs daemon & // launch the IPFS daemon
sleep 10 // wait for it to start
ipfs-update --dist-path /ipfs/QmVE4kPH5reJRvazaZwZK3Rrp95nGxkKtr253ZF6FJxVv9 // explicitly specify the ipfs path for dist.ipfs.io
```

However, it's probably easier just to download from github.

**Comment by zhjgit** [comment]
@Stebalien  
I use commands in ipfs v0.4.15
`ipfs-update --distpath /ipfs/QmVE4kPH5reJRvazaZwZK3Rrp95nGxkKtr253ZF6FJxVv9 install v0.4.22` 
The following error occurred，but upgrades are not a problem with ipfs v.0.4.18

![image](https://user-images.githubusercontent.com/11417141/63563869-374b6e00-c595-11e9-9654-ec4d4633335d.png)

**Comment by zhjgit** [comment]
`/ipfs/QmVE4kPH5reJRvazaZwZK3Rrp95nGxkKtr253ZF6FJxVv9` The gateway can not update and upgrade ipfs. I would like to ask if it can upgrade ipfs through binary files. Why do you have to upgrade the specified version online? @Stebalien

**Comment by zhjgit** [comment]
By modifying the gateway address
https://github.com/ipfs/ipfs-update/blob/4d18c479cdb739cb6fb53063041d589cb87a3586/util/utils.go#L22
 I recompiled `go-update`, which can now be upgraded online for go-ipfs v0.4.18. Because I am not familiar with go language, but I wonder if I can add a new function, the domain name configurable image` --distpath` can be customized, instead of hard coding in the program to specify that it must be `dist.ipfs.io`. The Possibility of Preventing Domain Names from Walling

**Comment by Stebalien** [comment]
>  The following error occurred，but upgrades are not a problem with ipfs v.0.4.18

This was a bug. Unfortunately, it was a bug in the update mechanism which made it a bit hard to retroactively fix.

> By modifying the gateway address

A `--gateway` flag would definitely be useful.

**Comment by hsanjuan** [comment]
This is a bit old. I'm closing it, but feel free to take a stab at a `--gateway` flag as proposed and submit a PR.
