### ISSUE TITLE
could not move old binary: permission denied 

### ISSUE THREAD

**Issue by axelsimon** [ipfs/ipfs-update#81]
Hi all,
On Fedora 27, I'm running into an error running `ipfs-update version latest`:
> ERROR: could not move old binary: remove /usr/local/bin/ipfs: permission denied 

Running `ls -hal /usr/local/bin/ipfs` gives:
> -rwx------. 1 axel axel 41M Nov 17 07:25 ipfs

I've added the `go/bin/` directory to my path and can call `ipfs-update` directly.
I've also modified the permissions on `/usr/local/bin/ipfs` to be as permissive as possible (777), no change in the error. I'm thinking there's possibly an an issue with SElinux preventing Go from touching things in `/usr/local/bin/`.

Here is the SElinux context:

> -rwx------. 1 axel axel unconfined_u:object_r:user_home_t:s0 41M Nov 17 07:25 /usr/local/bin/ipfs

Any clues welcome, my SElinux knowledge is limited :)

**Comment by hsanjuan** [comment]
Probably the permissions causing the issues are those of /usr/local/bin folder. Re-open if needed.

**Comment by SethranKada** [comment]
I'm having this issue too. Same error, though I'm using Fedora 36. I'm new to Linux and I don't know what to do to fix this.

**Comment by WeAreLegion999** [comment]
Face same issue. Used `sudo ipfs-update install latest` and problem was not there anymore
