### ISSUE TITLE
Installation fails on Linux

### ISSUE THREAD

**Issue by luav** [ipfs/ipfs-update#82]
Installation fails on Linux Ubuntu 16.04 x64 with go1.10 following the [instructions](https://ipfs.io/docs/install/#installing-with-ipfs-update):
```
/opt/saas$ go get -u github.com/ipfs/ipfs-update .

package _/opt/saas: unrecognized import path "_/opt/saas" (import path does not begin with hostname)
```

**Comment by Kubuxu** [comment]
I think the dot at the end is `end of the sentence` dot not part of the command.

**Comment by Kubuxu** [comment]
Should be resolved by: https://github.com/ipfs/website/pull/257

**Comment by luav** [comment]
Thanks, it works.
