### ISSUE TITLE
'ipfs update' doesn't do anything

### ISSUE THREAD

**Issue by nothingismagick** [ipfs/ipfs-update#83]
So I just posted an issue over at [go-ipfs](https://github.com/ipfs/go-ipfs/issues/4880) about the integration of this repo, and I wonder a little bit why on earth it I have to run it three times to get what I want. Should I have run `ipfs update fetch`? Or would that just have "fetched" the latest version and not installed it?

Why are there so many versions listed under `ipfs update versions`? Wouldn't 
```
v0.3.11
v0.4.14
```
be enough? 

```
~/.ipfs$ ipfs update
NAME:
   ipfs-update - Update ipfs.

USAGE:
   ipfs-update [global options] command [command options] [arguments...]

VERSION:
   1.5.3

COMMANDS:
     versions  Print out all available versions.
     version   Print out currently installed version.
     install   Install a version of ipfs.
     stash     stashes copy of currently installed ipfs binary
     revert    Revert to previously installed version of ipfs.
     fetch     Fetch a given version of ipfs. Default: latest.
     help, h   Shows a list of commands or help for one command

---------
~/.ipfs$ ipfs update versions
v0.3.2
v0.3.4
v0.3.5
v0.3.6
v0.3.7
v0.3.8
v0.3.9
v0.3.10
v0.3.11
v0.4.0
v0.4.1
v0.4.2
v0.4.3
v0.4.4
v0.4.5
v0.4.6
v0.4.7
v0.4.8
v0.4.9
v0.4.10
v0.4.11
v0.4.12
v0.4.13
v0.4.14-rc1
v0.4.14-rc2
v0.4.14-rc3
v0.4.14

----

~/.ipfs$ ipfs update install v0.4.14
fetching go-ipfs version v0.4.14
binary downloaded, verifying...
success! tests all passed.
stashing old binary
installing new binary to /home/magi/go/bin/ipfs
checking if repo migration is needed...

Installation complete!
```

**Comment by VictorBjelkholm** [comment]
> why on earth it I have to run it three times to get what I want

You don't, running `ipfs-update install v0.4.14` is enough if you want to install version 0.4.14.

> Should I have run ipfs update fetch?

That's only if you want the binary, but not to install it. Probably does not fit your use case, if you just want to install one new version but useful in testing and other cases.

> Why are there so many versions listed under ipfs update versions?

Hm, I don't see why we would limit it to just two versions? As it is, it lists the same as the versions we have available on the dist page, which is here: https://dist.ipfs.io/go-ipfs/

Again, useful when you want a specific version. Maybe to figure out where a bug was introduced, maybe to benchmark different versions. I don't see how providing _too many_ versions could be a problem.

**Comment by nothingismagick** [comment]
The reason I bring this up has a lot to do with [this document](https://ipfs.io/ipns/ipfs-docs-research.robbrackett.com/html/General-Notes.html) and specifically the "User Journey". I guess for the power-user and core-dev involved in go-ipfs you are absolutely right, no issues at all. 

My expectation as a new user is that a command listed in `ipfs --help` would not have to be additionally installed, and would not require anything other than running `ipfs update`. That is the reference I made in the title of this comment.

**Comment by VictorBjelkholm** [comment]
> I guess for the power-user and core-dev involved in go-ipfs you are absolutely right, no issues at all.

I'm not only talking about only power-users and core-devs, what I've found is that every version manager of languages/libraries/software in general exposes the very same commands. `download/fetch`, `versions` and `install`.

> My expectation as a new user is that a command listed in ipfs --help would not have to be additionally installed, and would not require anything other than running ipfs update. That is the reference I made in the title of this comment.

Ah, I understand better where you are coming from now. You're using `ipfs-update` via the `update` command on go-ipfs. The consideration change then.

`ipfs update` I agree, would just update to the latest version rather than showing the output of the `ipfs-update --help` command.

However, usually `upgrade` is used for actually installing updates (coming from at least Ubuntu/APT), while `update` would just fetch information about the downloads.

A possible flow would be to run `ipfs update` without any additional flags/arguments would check for a new version but not install it. Running `ipfs upgrade` would upgrade to the latest version found.

**Comment by nothingismagick** [comment]
Yes! Sorry if I didn't communicate that well enough about calling this from `go-ipfs` realm. 

I kind of expected `ipfs update` to work as syntactic sugar to call something like this one-liner (which I now know to be what happens):

```
$ ipfs update install $(ipfs update versions | sed '$!d')
```

`ipfs upgrade`is a brilliant idea.

**Comment by hsanjuan** [comment]
I am closing this as there are no actionables here and issue seems abandoned.
